### ISSUE TITLE
Warning from tidyr re unite_() deprecation

### ISSUE THREAD

**Issue by paulb20** [haleyjeppson/ggmosaic#60] opened 2022-02-25 11:40 UTC
Warning message:
`unite_()` was deprecated in tidyr 1.2.0.
Please use `unite()` instead.

Still works for now.

**Comment by GegznaV** [comment] 2022-02-27 16:38
I can reproduce this too:

![image](https://user-images.githubusercontent.com/12725868/155890503-a527cd1c-c01b-4f57-81eb-65aaa0f81c9b.png)

``` r
library(ggmosaic)
#> Loading required package: ggplot2
ggplot(data = titanic) +
  geom_mosaic(aes(x = product(Class, Age), fill = Survived))
#> Warning: `unite_()` was deprecated in tidyr 1.2.0.
#> Please use `unite()` instead.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
```

![](https://i.imgur.com/4Y0ebek.png)

<sup>Created on 2022-02-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

``` r
packageVersion("ggmosaic")
#> [1] ‘0.3.3’
```

**Comment by beerda** [comment] 2022-03-22 12:56
I confirm the presence of this warning too

**Comment by XiangyunHuang** [comment] 2022-10-02 14:33
I confirm the presence of this warning too.

**Comment by SAuderset** [comment] 2022-12-05 10:59
I get this warning as well, using R 4.2.2., tidyverse 1.3.2 and ggmosaic 0.3.3.

**Comment by jctourtellotte** [comment] 2023-01-11 19:36
"Warning: `unite_()` was deprecated in tidyr 1.2.0.
ℹ Please use `unite()` instead.
ℹ The deprecated feature was likely used in the ggmosaic package.
  Please report the issue at <https://github.com/haleyjeppson/ggmosaic>"
  
  This warning is an issue for me as well. 
  
R version 4.2.1 (2022-06-23)
ggmosaic version 0.3.3
tidyverse version 1.3.2

**Comment by jpmam1** [comment] 2023-06-19 01:36
This warning occurs in the CRAN version but it's fixed in the dev version.

You can install the updated version using:
 ```
# install.packages("devtools")
devtools::install_github("haleyjeppson/ggmosaic")
```

**Comment by nicholasjhorton** [comment] 2023-07-23 23:24
Thanks for the fix: that's greatly appreciated.

Do you have plans to update the version on CRAN?

**Comment by PiyuminbKM** [comment] 2023-11-09 18:25
I tried the fix above (devtools::install_github("haleyjeppson/ggmosaic"))
 but it gives me the following error
 "Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘pkgload’ 1.2.4 is being loaded, but >= 1.3.0 is required

Can someone help me with fixing this, I really need the pretty Mosaic plot for my project.

**Comment by Jtrachsel** [comment] 2023-11-09 18:54
@PiyuminbKM looks like you need to update your `pkgload` installation. try this:
`install.packages('pkgload')`
`devtools::install_github("haleyjeppson/ggmosaic")`

**Comment by averissimo** [comment] 2024-02-26 14:12
This has been fixed for 2 years. Is a new release around the corner? :smile:

**Closed** 2024-10-01 12:39 UTC
